feeder: dataset.dataloader_video.BaseFeeder
phase: test
dataset: phoenix14
# dataset: phoenix14-si5
num_epoch: 10
work_dir: ./work_dir/CSL_8/
batch_size: 4
random_seed: 0
test_batch_size: 4
num_worker: 10
device: 0,1
log_interval: 50
eval_interval: 1
save_interval: 2
# python in default
evaluate_tool: python
loss_weights:
  ConvCTC: 1.0
  SeqCTC: 1.0
  Dist: 10.0
  MergeCTC: 3.0
load_weights: ./work_dir/CSL_5/test_03.11_epoch30_model.pt

optimizer_args:
  optimizer: Adam     #Adam、SGD、Plateau
  base_lr: 0.0001
  step: [ 2, 4]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

model: slr_network.SLRModel
decode_mode: beam

model_args:
  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1
